### PR TITLE
[HOPSWORKS-1276] Anaconda import yml file not working, removal of explicitly enabling python kernel

### PR DESCRIPTION
**Pull request by robzor92**
…licit enabling of python kernel

## Make sure there is no duplicate PR for this issue

* **Please check if the PR meets the following requirements**
- [ ] Adds tests for the submitted changes (for bug fixes & features)
- [x] Passes the tests
- [x] HOPSWORKS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit

* **Post a link to the associated JIRA issue**

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by robzor92** [comment]
https://github.com/logicalclocks/hops-testing/pull/497

**Comment by robzor92** [comment]
@ErmiasG please review.

**Comment by tkakantousis** [comment]
@robzor92 if there are UI changes, can you provide screenshots showing the new UI?

**Comment by robzor92** [comment]
Enabling Anaconda - Old (The dropdown did not close when you selected a version)
enable_anaconda_old

Enabling Anaconda - New
Screenshot from 2019-09-18 09-08-19

**Comment by robzor92** [comment]
Old selecting a .yml file
Screenshot from 2019-09-18 09-18-01

New selecting a .yml file
Screenshot from 2019-09-18 09-18-42

**Comment by robzor92** [comment]
@tkakantousis @SirOibaf @ErmiasG the "install jupyter" option is broken i found out. For some reason we use tqdm and hops in sparkmagic now so I have to add them.

**Comment by jimdowling** [comment]
sparkmagic is using tqdm for maggy to display experiment trials in a nice visual way. I am not aware of hops being included in sparkmagic.

**Comment by robzor92** [comment]
> sparkmagic is using tqdm for maggy to display experiment trials in a nice visual way. I am not aware of hops being included in sparkmagic.

It assumes hops is in the environment, see this: https://github.com/logicalclocks/sparkmagic/blob/617b820727c587afd37cf8cf2418da48c3e94ebd/sparkmagic/sparkmagic/magics/sparkmagicsbase.py#L26

**Comment by jimdowling** [comment]
Is having hops in the environment a problem? I can see that it only uses constants from the hops library. We can assume that sparkmagic will only be installed on a jupyter server - either on the hopsworks server or on a kubernetes/docker instance owned by Hopsworks.

**Comment by robzor92** [comment]
Remove Environment moved to Installed Python Libraries
Screenshot from 2019-09-24 10-29-18

**Comment by kouzant** [comment]
@robzor92 what's the `Install Jupyter` button doing? Will it be affected when I merge JupyterLab?

**Comment by robzor92** [comment]
[Fix importing .yml as Anaconda env](https://trello.com/c/eATlpclT/5-fix-importing-yml-as-anaconda-env)

**Pull request merged**
