### PR TITLE
[HOPSWORKS-1070] Refactor HdfsLeDescriptorsFacade to return a random NN for bootstrapping the client

### PR DESCRIPTION
**Pull request by robzor92**
…ing the client

## Make sure there is no duplicate PR for this issue

* **Please check if the PR meets the following requirements**
- [ ] Adds tests for the submitted changes (for bug fixes & features)
- [ ] Passes the tests
- [x] HOPSWORKS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit

* **Post a link to the associated JIRA issue**

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by robzor92** [comment]
https://github.com/logicalclocks/hops-testing/pull/377

**Comment by robzor92** [comment]
@tkakantousis @SirOibaf please review.

**Comment by kouzant** [comment]
@robzor92 In HDFSUIProxyServlet we get the HTTP address of the NameNode from the Variables table. Could you fix that so it gets the Leader NN from the LE protocol instead of the variables table? In that case you won't have to change the entry manually

**Comment by robzor92** [comment]
> @robzor92 In HDFSUIProxyServlet we get the HTTP address of the NameNode from the Variables table. Could you fix that so it gets the Leader NN from the LE protocol instead of the variables table? In that case you won't have to change the entry manually

Sure I can look into it, does it have to be the leader NN?

**Comment by kouzant** [comment]
Yes it is better if we redirect always to the Leader. We would have a consistent UI

**Comment by robzor92** [comment]
This will require changes to Hops since currently the ip address of the  http_address set on the HdfsLeDescriptors is 0.0.0.0, so will be tracked in a separate Jira.

**Pull request merged**
